import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from '../components/NavBar';
import theme from '../theme/theme';
import { ThemeProvider } from '@mui/material';
import './layout.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'ToDoList with NextJs',
	description: 'Generated by create next app',
	icons: {
		icon: '../../public/favicon.ico',
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider theme={theme}>
					<NavBar />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
