'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from './components/NavBar';
import theme from './theme';
import { Stack, Theme, ThemeProvider, styled } from '@mui/material';
import './layout.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'ToDoList with NextJs',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider theme={theme}>
					<StyledStack>
						<NavBar />
						{children}
					</StyledStack>
				</ThemeProvider>
			</body>
		</html>
	);
}

const StyledStack = styled(Stack)(({ theme }: { theme: Theme }) => ({
	backgroundColor: theme.palette.BackgroundColors.dark,
	height: typeof window !== undefined ? window.innerHeight : '100%',
}));
