import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navigation from './navigation/navigation';
import Theme from './ui/Theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'ToDoList with NextJs',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body style={{ margin: '0px' }} className={inter.className}>
				<div style={{ backgroundColor: '#edeef0' }}>
					<Theme>
						<Navigation />
						{children}
					</Theme>
				</div>
			</body>
		</html>
	);
}
